# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['10.148.0.9:9093']      

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - alert.rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  # add  : grab stats about the local machine by [node-exporter]
  - job_name: system_monitor
    static_configs:
      - targets: ['10.148.0.9:9100','35.186.x.x:9100','35.247.x.x:9100','35.198.x.x:9100']


  - job_name: service_monitor
    static_configs:
      - targets: ['35.186.x.x:9216','35.247.x.x:9216','35.198.x.x:9216','10.148.0.9:9216','10.148.0.9:9215']

  
  - job_name: kubernetes
    static_configs:
      - targets: ['34.102.x.x']
  

  - job_name: x_production
    static_configs:
      - targets: ['35.247.x.x:9100','35.240.x.x:9100','34.87.x.x:9100','34.87.x.x:9100','35.247.x.x:9100','34.126.x.x:9100']      
  
  - job_name: y_staging
    static_configs:
      - targets: ['35.186.y.y:9100','34.126.y.y:9100','34.126.y.y:9100','35.240.y.y:9100','34.87.y.y:9100','35.240.y.y:9100']
